// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: FactoryNode5

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_ATSFactoryNode
void ui_ATSFactoryNode_screen_init(void);
lv_obj_t * ui_ATSFactoryNode;
lv_obj_t * ui_mainTab;
lv_obj_t * ui_HomeTab;
lv_obj_t * ui_HomeTabPanel;
lv_obj_t * ui_Label3;
lv_obj_t * ui_StartWorkOrderTab;
lv_obj_t * ui_StartWorkOrderTabPanel;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Container2;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Container3;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Container4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Container5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Container11;
lv_obj_t * ui_Label11;
lv_obj_t * ui_Container12;
lv_obj_t * ui_Label12;
lv_obj_t * ui_Container6;
lv_obj_t * ui_Container7;
lv_obj_t * ui_Label7;
lv_obj_t * ui_Container13;
lv_obj_t * ui_Label8;
lv_obj_t * ui_Container8;
lv_obj_t * ui_Container9;
lv_obj_t * ui_Container10;
lv_obj_t * ui_Container14;
lv_obj_t * ui_StartWorkOrder;
lv_obj_t * ui_Label9;
lv_obj_t * ui_FinishWorkOverTab;
lv_obj_t * ui_FinishWorkOrderTabPanel;
lv_obj_t * ui_QAWorkOrderTab;
lv_obj_t * ui_QAWorkOrderTabPanel;
lv_obj_t * ui_ShippingWorkOrderTab;
lv_obj_t * ui_ShippingWorkOrderTabPanel;
lv_obj_t * ui_InfoTab;
lv_obj_t * ui_InfoTabPanel;
lv_obj_t * ui_ScanQRCodeButton;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Image1;
lv_obj_t * ui_ImageWIFI0;
lv_obj_t * ui_ImageWIFI1;
lv_obj_t * ui_ImageWIFI2;
lv_obj_t * ui_ImageWIFI3;
lv_obj_t * ui_WIFINotConnected;
lv_obj_t * ui_WIFIConnecting;
lv_obj_t * ui_WIFIConnected;
lv_obj_t * ui_WIFIIPaddress;
lv_obj_t * ui_Spinner1;
lv_obj_t * ui_Label13;
// CUSTOM VARIABLES


// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
lv_obj_t * ui_Settings;
lv_obj_t * ui_Image2;
lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_wifi[4] = {&ui_img_wifi0_png, &ui_img_wifi1_png, &ui_img_wifi2_png, &ui_img_wifi3_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_ATSFactoryNode_screen_init();
    ui_Settings_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_ATSFactoryNode);
}
