// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: FactoryNode5

#ifndef _FACTORYNODE5_UI_H
#define _FACTORYNODE5_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


// SCREEN: ui_ATSFactoryNode
void ui_ATSFactoryNode_screen_init(void);
extern lv_obj_t * ui_ATSFactoryNode;
extern lv_obj_t * ui_mainTab;
extern lv_obj_t * ui_HomeTab;
extern lv_obj_t * ui_HomeTabPanel;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_StartWorkOrderTab;
extern lv_obj_t * ui_StartWorkOrderTabPanel;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Container4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Container11;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_Container12;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_Container6;
extern lv_obj_t * ui_Container7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Container13;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_Container8;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_Container10;
extern lv_obj_t * ui_Container14;
extern lv_obj_t * ui_StartWorkOrder;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_FinishWorkOverTab;
extern lv_obj_t * ui_FinishWorkOrderTabPanel;
extern lv_obj_t * ui_QAWorkOrderTab;
extern lv_obj_t * ui_QAWorkOrderTabPanel;
extern lv_obj_t * ui_ShippingWorkOrderTab;
extern lv_obj_t * ui_ShippingWorkOrderTabPanel;
extern lv_obj_t * ui_InfoTab;
extern lv_obj_t * ui_InfoTabPanel;
extern lv_obj_t * ui_ScanQRCodeButton;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Image1;
extern lv_obj_t * ui_ImageWIFI0;
extern lv_obj_t * ui_ImageWIFI1;
extern lv_obj_t * ui_ImageWIFI2;
extern lv_obj_t * ui_ImageWIFI3;
extern lv_obj_t * ui_WIFINotConnected;
extern lv_obj_t * ui_WIFIConnecting;
extern lv_obj_t * ui_WIFIConnected;
extern lv_obj_t * ui_WIFIIPaddress;
extern lv_obj_t * ui_Spinner1;
extern lv_obj_t * ui_Label13;
// CUSTOM VARIABLES

// SCREEN: ui_Settings
void ui_Settings_screen_init(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label10;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_207335009);    // assets/ATS-Logo.png
LV_IMG_DECLARE(ui_img_wifi0_png);    // assets/wifi0.png
LV_IMG_DECLARE(ui_img_wifi1_png);    // assets/wifi1.png
LV_IMG_DECLARE(ui_img_wifi2_png);    // assets/wifi2.png
LV_IMG_DECLARE(ui_img_wifi3_png);    // assets/wifi3.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
