// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: FactoryNode5

#include "ui.h"

void ui_ATSFactoryNode_screen_init(void)
{
    ui_ATSFactoryNode = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ATSFactoryNode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainTab = lv_tabview_create(ui_ATSFactoryNode, LV_DIR_TOP, 50);
    lv_obj_set_height(ui_mainTab, 315);
    lv_obj_set_width(ui_mainTab, lv_pct(98));
    lv_obj_set_x(ui_mainTab, 0);
    lv_obj_set_y(ui_mainTab, -60);
    lv_obj_set_align(ui_mainTab, LV_ALIGN_BOTTOM_MID);
    lv_obj_clear_flag(ui_mainTab, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_mainTab, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);


    ui_HomeTab = lv_tabview_add_tab(ui_mainTab, "Home");

    ui_HomeTabPanel = lv_obj_create(ui_HomeTab);
    lv_obj_set_width(ui_HomeTabPanel, 772);
    lv_obj_set_height(ui_HomeTabPanel, 261);
    lv_obj_set_x(ui_HomeTabPanel, -6);
    lv_obj_set_y(ui_HomeTabPanel, 0);
    lv_obj_set_align(ui_HomeTabPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_HomeTabPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_HomeTabPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_HomeTabPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_HomeTabPanel);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -109);
    lv_obj_set_y(ui_Label3, 1);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "To start the process please scan \nthe barcode on the Work Order");
    lv_obj_set_style_text_font(ui_Label3, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartWorkOrderTab = lv_tabview_add_tab(ui_mainTab, "Start WO");

    ui_StartWorkOrderTabPanel = lv_obj_create(ui_StartWorkOrderTab);
    lv_obj_set_width(ui_StartWorkOrderTabPanel, 772);
    lv_obj_set_height(ui_StartWorkOrderTabPanel, 261);
    lv_obj_set_x(ui_StartWorkOrderTabPanel, -6);
    lv_obj_set_y(ui_StartWorkOrderTabPanel, 0);
    lv_obj_set_align(ui_StartWorkOrderTabPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StartWorkOrderTabPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_StartWorkOrderTabPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_StartWorkOrderTabPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_StartWorkOrderTabPanel);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 730);
    lv_obj_set_height(ui_Container1, 30);
    lv_obj_set_x(ui_Container1, -26);
    lv_obj_set_y(ui_Container1, -1);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container2 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 100);
    lv_obj_set_height(ui_Container2, 25);
    lv_obj_set_x(ui_Container2, -26);
    lv_obj_set_y(ui_Container2, -1);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_Container2);
    lv_obj_set_width(ui_Label4, 100);
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Register:");

    ui_Container3 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 100);
    lv_obj_set_height(ui_Container3, 30);
    lv_obj_set_x(ui_Container3, -26);
    lv_obj_set_y(ui_Container3, -10);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "29050");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 110);
    lv_obj_set_height(ui_Container4, 25);
    lv_obj_set_x(ui_Container4, -26);
    lv_obj_set_y(ui_Container4, -1);
    lv_obj_set_align(ui_Container4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container4, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container4, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Line Item:");

    ui_Container5 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 100);
    lv_obj_set_height(ui_Container5, 25);
    lv_obj_set_x(ui_Container5, -26);
    lv_obj_set_y(ui_Container5, -1);
    lv_obj_set_align(ui_Container5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container5, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "1-1a");
    lv_obj_set_style_text_font(ui_Label6, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container11 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container11);
    lv_obj_set_width(ui_Container11, 100);
    lv_obj_set_height(ui_Container11, 25);
    lv_obj_set_x(ui_Container11, -26);
    lv_obj_set_y(ui_Container11, -1);
    lv_obj_set_align(ui_Container11, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container11, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container11, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label11 = lv_label_create(ui_Container11);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "Status:");

    ui_Container12 = lv_obj_create(ui_Container1);
    lv_obj_remove_style_all(ui_Container12);
    lv_obj_set_width(ui_Container12, 215);
    lv_obj_set_height(ui_Container12, 25);
    lv_obj_set_x(ui_Container12, -26);
    lv_obj_set_y(ui_Container12, -1);
    lv_obj_set_align(ui_Container12, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container12, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container12, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_Container12);
    lv_obj_set_width(ui_Label12, 225);
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label12, 24);
    lv_obj_set_y(ui_Label12, 0);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "NOT STARTED");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Label12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_StartWorkOrderTabPanel);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 730);
    lv_obj_set_height(ui_Container6, 30);
    lv_obj_set_x(ui_Container6, -26);
    lv_obj_set_y(ui_Container6, -1);
    lv_obj_set_align(ui_Container6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container6, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container6, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 150);
    lv_obj_set_height(ui_Container7, 25);
    lv_obj_set_x(ui_Container7, -26);
    lv_obj_set_y(ui_Container7, -1);
    lv_obj_set_align(ui_Container7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container7, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container7, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_Label7, 150);
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label7, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Label7, "ATS Part No:");

    ui_Container13 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container13);
    lv_obj_set_width(ui_Container13, 200);
    lv_obj_set_height(ui_Container13, 25);
    lv_obj_set_x(ui_Container13, -26);
    lv_obj_set_y(ui_Container13, -1);
    lv_obj_set_align(ui_Container13, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container13, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container13, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Container13);
    lv_obj_set_width(ui_Label8, 150);
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 24);
    lv_obj_set_y(ui_Label8, 1);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label8, LV_LABEL_LONG_DOT);
    lv_label_set_text(ui_Label8, "261000");
    lv_obj_set_style_text_font(ui_Label8, &lv_font_montserrat_26, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 100);
    lv_obj_set_height(ui_Container8, 25);
    lv_obj_set_x(ui_Container8, -26);
    lv_obj_set_y(ui_Container8, -1);
    lv_obj_set_align(ui_Container8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container8, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 110);
    lv_obj_set_height(ui_Container9, 25);
    lv_obj_set_x(ui_Container9, -26);
    lv_obj_set_y(ui_Container9, -1);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container9, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Container6);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 100);
    lv_obj_set_height(ui_Container10, 25);
    lv_obj_set_x(ui_Container10, -26);
    lv_obj_set_y(ui_Container10, -1);
    lv_obj_set_align(ui_Container10, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container10, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Container10, lv_color_hex(0xEEEEEE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Container10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container14 = lv_obj_create(ui_StartWorkOrderTabPanel);
    lv_obj_remove_style_all(ui_Container14);
    lv_obj_set_width(ui_Container14, 730);
    lv_obj_set_height(ui_Container14, 139);
    lv_obj_set_x(ui_Container14, -26);
    lv_obj_set_y(ui_Container14, -1);
    lv_obj_set_align(ui_Container14, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_StartWorkOrder = lv_btn_create(ui_Container14);
    lv_obj_set_width(ui_StartWorkOrder, 400);
    lv_obj_set_height(ui_StartWorkOrder, 50);
    lv_obj_set_align(ui_StartWorkOrder, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_add_flag(ui_StartWorkOrder, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StartWorkOrder, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label9 = lv_label_create(ui_StartWorkOrder);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "Start Work Order");
    lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_34, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FinishWorkOverTab = lv_tabview_add_tab(ui_mainTab, "Finish WO");

    ui_FinishWorkOrderTabPanel = lv_obj_create(ui_FinishWorkOverTab);
    lv_obj_set_width(ui_FinishWorkOrderTabPanel, 772);
    lv_obj_set_height(ui_FinishWorkOrderTabPanel, 261);
    lv_obj_set_x(ui_FinishWorkOrderTabPanel, -6);
    lv_obj_set_y(ui_FinishWorkOrderTabPanel, 0);
    lv_obj_set_align(ui_FinishWorkOrderTabPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_FinishWorkOrderTabPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_FinishWorkOrderTabPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_FinishWorkOrderTabPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_QAWorkOrderTab = lv_tabview_add_tab(ui_mainTab, "QA WO");

    ui_QAWorkOrderTabPanel = lv_obj_create(ui_QAWorkOrderTab);
    lv_obj_set_width(ui_QAWorkOrderTabPanel, 772);
    lv_obj_set_height(ui_QAWorkOrderTabPanel, 261);
    lv_obj_set_x(ui_QAWorkOrderTabPanel, -6);
    lv_obj_set_y(ui_QAWorkOrderTabPanel, 0);
    lv_obj_set_align(ui_QAWorkOrderTabPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_QAWorkOrderTabPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_QAWorkOrderTabPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_QAWorkOrderTabPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ShippingWorkOrderTab = lv_tabview_add_tab(ui_mainTab, "Shipping");

    ui_ShippingWorkOrderTabPanel = lv_obj_create(ui_ShippingWorkOrderTab);
    lv_obj_set_width(ui_ShippingWorkOrderTabPanel, 772);
    lv_obj_set_height(ui_ShippingWorkOrderTabPanel, 261);
    lv_obj_set_x(ui_ShippingWorkOrderTabPanel, -6);
    lv_obj_set_y(ui_ShippingWorkOrderTabPanel, 0);
    lv_obj_set_align(ui_ShippingWorkOrderTabPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ShippingWorkOrderTabPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ShippingWorkOrderTabPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ShippingWorkOrderTabPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_InfoTab = lv_tabview_add_tab(ui_mainTab, "Info");

    ui_InfoTabPanel = lv_obj_create(ui_InfoTab);
    lv_obj_set_width(ui_InfoTabPanel, 772);
    lv_obj_set_height(ui_InfoTabPanel, 261);
    lv_obj_set_x(ui_InfoTabPanel, -6);
    lv_obj_set_y(ui_InfoTabPanel, 0);
    lv_obj_set_align(ui_InfoTabPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_InfoTabPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_InfoTabPanel, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_InfoTabPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScanQRCodeButton = lv_btn_create(ui_ATSFactoryNode);
    lv_obj_set_width(ui_ScanQRCodeButton, 288);
    lv_obj_set_height(ui_ScanQRCodeButton, 50);
    lv_obj_set_x(ui_ScanQRCodeButton, 5);
    lv_obj_set_y(ui_ScanQRCodeButton, -5);
    lv_obj_set_align(ui_ScanQRCodeButton, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_ScanQRCodeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ScanQRCodeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ScanQRCodeButton);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SCAN QR CODE");
    lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image1 = lv_img_create(ui_ATSFactoryNode);
    lv_img_set_src(ui_Image1, &ui_img_207335009);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 187
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_Image1, -299);
    lv_obj_set_y(ui_Image1, -188);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWIFI0 = lv_img_create(ui_ATSFactoryNode);
    lv_img_set_src(ui_ImageWIFI0, &ui_img_wifi0_png);
    lv_obj_set_width(ui_ImageWIFI0, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ImageWIFI0, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_ImageWIFI0, -2);
    lv_obj_set_y(ui_ImageWIFI0, 2);
    lv_obj_set_align(ui_ImageWIFI0, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWIFI0, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWIFI0, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWIFI1 = lv_img_create(ui_ATSFactoryNode);
    lv_img_set_src(ui_ImageWIFI1, &ui_img_wifi1_png);
    lv_obj_set_width(ui_ImageWIFI1, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ImageWIFI1, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_ImageWIFI1, -2);
    lv_obj_set_y(ui_ImageWIFI1, 2);
    lv_obj_set_align(ui_ImageWIFI1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWIFI1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWIFI1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWIFI2 = lv_img_create(ui_ATSFactoryNode);
    lv_img_set_src(ui_ImageWIFI2, &ui_img_wifi2_png);
    lv_obj_set_width(ui_ImageWIFI2, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ImageWIFI2, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_ImageWIFI2, -1);
    lv_obj_set_y(ui_ImageWIFI2, 2);
    lv_obj_set_align(ui_ImageWIFI2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWIFI2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWIFI2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ImageWIFI3 = lv_img_create(ui_ATSFactoryNode);
    lv_img_set_src(ui_ImageWIFI3, &ui_img_wifi3_png);
    lv_obj_set_width(ui_ImageWIFI3, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_ImageWIFI3, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_ImageWIFI3, -2);
    lv_obj_set_y(ui_ImageWIFI3, 2);
    lv_obj_set_align(ui_ImageWIFI3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_ImageWIFI3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageWIFI3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WIFINotConnected = lv_label_create(ui_ATSFactoryNode);
    lv_obj_set_width(ui_WIFINotConnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFINotConnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFINotConnected, -5);
    lv_obj_set_y(ui_WIFINotConnected, -5);
    lv_obj_set_align(ui_WIFINotConnected, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_WIFINotConnected, "Not Connected to WI-FI");
    lv_obj_set_style_text_color(ui_WIFINotConnected, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WIFINotConnected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIConnecting = lv_label_create(ui_ATSFactoryNode);
    lv_obj_set_width(ui_WIFIConnecting, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFIConnecting, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFIConnecting, -5);
    lv_obj_set_y(ui_WIFIConnecting, -5);
    lv_obj_set_align(ui_WIFIConnecting, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_WIFIConnecting, "Connecting to WI-FI");
    lv_obj_add_flag(ui_WIFIConnecting, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_WIFIConnecting, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WIFIConnecting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIConnected = lv_label_create(ui_ATSFactoryNode);
    lv_obj_set_width(ui_WIFIConnected, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFIConnected, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFIConnected, -5);
    lv_obj_set_y(ui_WIFIConnected, -5);
    lv_obj_set_align(ui_WIFIConnected, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_WIFIConnected, "Connected to WI-FI");
    lv_obj_add_flag(ui_WIFIConnected, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_WIFIConnected, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WIFIConnected, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WIFIIPaddress = lv_label_create(ui_ATSFactoryNode);
    lv_obj_set_width(ui_WIFIIPaddress, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WIFIIPaddress, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WIFIIPaddress, -5);
    lv_obj_set_y(ui_WIFIIPaddress, -20);
    lv_obj_set_align(ui_WIFIIPaddress, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_WIFIIPaddress, "192.168.107.199");
    lv_obj_add_flag(ui_WIFIIPaddress, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_WIFIIPaddress, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WIFIIPaddress, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Spinner1 = lv_spinner_create(ui_ATSFactoryNode, 1000, 90);
    lv_obj_set_width(ui_Spinner1, 80);
    lv_obj_set_height(ui_Spinner1, 80);
    lv_obj_set_x(ui_Spinner1, -14);
    lv_obj_set_y(ui_Spinner1, 30);
    lv_obj_set_align(ui_Spinner1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Spinner1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Spinner1, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Label13 = lv_label_create(ui_ATSFactoryNode);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 30);
    lv_obj_set_y(ui_Label13, 36);
    lv_obj_set_align(ui_Label13, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label13, "ATS Factory Node 01");
    lv_obj_set_style_text_font(ui_Label13, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);


}
