// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: FactoryNode5

#include "ui.h"

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image2 = lv_img_create(ui_Settings);
    lv_img_set_src(ui_Image2, &ui_img_207335009);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 187
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 90
    lv_obj_set_x(ui_Image2, -302);
    lv_obj_set_y(ui_Image2, -190);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, -42);
    lv_obj_set_y(ui_Label10, -188);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "Settings");
    lv_obj_set_style_text_font(ui_Label10, &lv_font_montserrat_38, LV_PART_MAIN | LV_STATE_DEFAULT);


}
